org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# NeoGradle's NeoForm pipeline does not restore its generated patch directory correctly after clean
# when the Gradle configuration cache is reused.
org.gradle.configuration-cache=false

# Platform dependencies
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.84
jei_version=30.32.0.209

mod_id=acidglows_ingame_recipe_editor
mod_name=Acidglow's Ingame Recipe Editor
mod_license=MIT
mod_version=1.0.0
mod_group_id=acidglow.ingamerecipeeditor
